manifest:
  remotes:
    - name: nrfcloud
      url-base: https://github.com/nRFCloud
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: origin
      url-base: https://github.com/plskeggs
  projects:
    - name: sdk-nrf
      path: nrf
      remote: origin
      revision: feature-management-interface
      import: true
  self:
    path: lte-gateway-ble

